jdtapp.r5mysql/config/routes.rb
Rails.application.routes.draw do
  resources :jdt2s
  resources :ojdts
  resources :jdt1s
  resources :ttts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

jdtapp.r5mysql/app/models/ojdt.rb
class Ojdt < ApplicationRecord
end

jdtapp.r5mysql/app/controllers/ojdts_controller.rb
class OjdtsController < ApplicationController
  before_action :set_ojdt, only: [:show, :edit, :update, :destroy]

  # GET /ojdts
  # GET /ojdts.json
  def index
    @ojdts = Ojdt.all
  end

  # GET /ojdts/1
  # GET /ojdts/1.json
  def show
  end

  # GET /ojdts/new
  def new
    @ojdt = Ojdt.new
  end

  # GET /ojdts/1/edit
  def edit
  end

  # POST /ojdts
  # POST /ojdts.json
  def create
    @ojdt = Ojdt.new(ojdt_params)

    respond_to do |format|
      if @ojdt.save
        format.html { redirect_to @ojdt, notice: 'Ojdt was successfully created.' }
        format.json { render :show, status: :created, location: @ojdt }
      else
        format.html { render :new }
        format.json { render json: @ojdt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ojdts/1
  # PATCH/PUT /ojdts/1.json
  def update
    respond_to do |format|
      if @ojdt.update(ojdt_params)
        format.html { redirect_to @ojdt, notice: 'Ojdt was successfully updated.' }
        format.json { render :show, status: :ok, location: @ojdt }
      else
        format.html { render :edit }
        format.json { render json: @ojdt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ojdts/1
  # DELETE /ojdts/1.json
  def destroy
    @ojdt.destroy
    respond_to do |format|
      format.html { redirect_to ojdts_url, notice: 'Ojdt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ojdt
      @ojdt = Ojdt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ojdt_params
      params.require(:ojdt).permit(:BatchNum, :TransId, :BtfStatus, :TransType, :BaseRef, :RefDate, :Memo, :Ref1, :Ref2, :CreatedBy, :LocTotal, :FcTotal, :SysTotal, :TransCode, :OrignCurr, :TransRate, :BtfLine, :TransCurr, :Project, :DueDate, :TaxDate, :PCAddition, :FinncPriod, :DataSource, :UpdateDate, :CreateDate, :UserSign, :UserSign2, :RefndRprt, :LogInstanc, :ObjType, :Indicator, :AdjTran, :RevSource, :StornoDate, :StornoToTr, :AutoStorno, :Corisptivi, :VatDate, :StampTax, :Series, :Number, :AutoVAT, :DocSeries, :FolioPref, :FolioNum, :CreateTime, :BlockDunn, :ReportEU, :Report347, :Printed, :DocType, :AttNum, :GenRegNo, :RG23APart2, :RG23CPart2, :MatType, :Creator, :Approver, :Location, :SeqCode, :Serial, :SeriesStr, :SubStr, :AutoWT, :WTSum, :WTSumSC, :WTSumFC, :WTApplied, :WTAppliedS, :WTAppliedF, :BaseAmnt, :BaseAmntSC, :BaseAmntFC, :BaseVtAt, :BaseVtAtSC, :BaseVtAtFC, :VersionNum, :BaseTrans, :ResidenNum, :OperatCode, :Ref3, :SSIExmpt, :SignMsg, :SignDigest, :CertifNum, :KeyVersion, :CUP, :CIG, :SupplCode, :SPSrcType, :SPSrcID, :SPSrcDLN, :DeferedTax, :AgrNo, :SeqNum)
    end
end

jdtapp.r5mysql/app/helpers/ojdts_helper.rb
module OjdtsHelper
end

jdtapp.r5mysql/app/views/ojdts/edit.html.erb
<h1>Editing Ojdt</h1>

<%= render 'form', ojdt: @ojdt %>

<%= link_to 'Show', @ojdt %> |
<%= link_to 'Back', ojdts_path %>

jdtapp.r5mysql/app/views/ojdts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ojdts</h1>

<table>
  <thead>
    <tr>
      <th>Batchnum</th>
      <th>Transid</th>
      <th>Btfstatus</th>
      <th>Transtype</th>
      <th>Baseref</th>
      <th>Refdate</th>
      <th>Memo</th>
      <th>Ref1</th>
      <th>Ref2</th>
      <th>Createdby</th>
      <th>Loctotal</th>
      <th>Fctotal</th>
      <th>Systotal</th>
      <th>Transcode</th>
      <th>Origncurr</th>
      <th>Transrate</th>
      <th>Btfline</th>
      <th>Transcurr</th>
      <th>Project</th>
      <th>Duedate</th>
      <th>Taxdate</th>
      <th>Pcaddition</th>
      <th>Finncpriod</th>
      <th>Datasource</th>
      <th>Updatedate</th>
      <th>Createdate</th>
      <th>Usersign</th>
      <th>Usersign2</th>
      <th>Refndrprt</th>
      <th>Loginstanc</th>
      <th>Objtype</th>
      <th>Indicator</th>
      <th>Adjtran</th>
      <th>Revsource</th>
      <th>Stornodate</th>
      <th>Stornototr</th>
      <th>Autostorno</th>
      <th>Corisptivi</th>
      <th>Vatdate</th>
      <th>Stamptax</th>
      <th>Series</th>
      <th>Number</th>
      <th>Autovat</th>
      <th>Docseries</th>
      <th>Foliopref</th>
      <th>Folionum</th>
      <th>Createtime</th>
      <th>Blockdunn</th>
      <th>Reporteu</th>
      <th>Report347</th>
      <th>Printed</th>
      <th>Doctype</th>
      <th>Attnum</th>
      <th>Genregno</th>
      <th>Rg23apart2</th>
      <th>Rg23cpart2</th>
      <th>Mattype</th>
      <th>Creator</th>
      <th>Approver</th>
      <th>Location</th>
      <th>Seqcode</th>
      <th>Serial</th>
      <th>Seriesstr</th>
      <th>Substr</th>
      <th>Autowt</th>
      <th>Wtsum</th>
      <th>Wtsumsc</th>
      <th>Wtsumfc</th>
      <th>Wtapplied</th>
      <th>Wtapplieds</th>
      <th>Wtappliedf</th>
      <th>Baseamnt</th>
      <th>Baseamntsc</th>
      <th>Baseamntfc</th>
      <th>Basevtat</th>
      <th>Basevtatsc</th>
      <th>Basevtatfc</th>
      <th>Versionnum</th>
      <th>Basetrans</th>
      <th>Residennum</th>
      <th>Operatcode</th>
      <th>Ref3</th>
      <th>Ssiexmpt</th>
      <th>Signmsg</th>
      <th>Signdigest</th>
      <th>Certifnum</th>
      <th>Keyversion</th>
      <th>Cup</th>
      <th>Cig</th>
      <th>Supplcode</th>
      <th>Spsrctype</th>
      <th>Spsrcid</th>
      <th>Spsrcdln</th>
      <th>Deferedtax</th>
      <th>Agrno</th>
      <th>Seqnum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ojdts.each do |ojdt| %>
      <tr>
        <td><%= ojdt.BatchNum %></td>
        <td><%= ojdt.TransId %></td>
        <td><%= ojdt.BtfStatus %></td>
        <td><%= ojdt.TransType %></td>
        <td><%= ojdt.BaseRef %></td>
        <td><%= ojdt.RefDate %></td>
        <td><%= ojdt.Memo %></td>
        <td><%= ojdt.Ref1 %></td>
        <td><%= ojdt.Ref2 %></td>
        <td><%= ojdt.CreatedBy %></td>
        <td><%= ojdt.LocTotal %></td>
        <td><%= ojdt.FcTotal %></td>
        <td><%= ojdt.SysTotal %></td>
        <td><%= ojdt.TransCode %></td>
        <td><%= ojdt.OrignCurr %></td>
        <td><%= ojdt.TransRate %></td>
        <td><%= ojdt.BtfLine %></td>
        <td><%= ojdt.TransCurr %></td>
        <td><%= ojdt.Project %></td>
        <td><%= ojdt.DueDate %></td>
        <td><%= ojdt.TaxDate %></td>
        <td><%= ojdt.PCAddition %></td>
        <td><%= ojdt.FinncPriod %></td>
        <td><%= ojdt.DataSource %></td>
        <td><%= ojdt.UpdateDate %></td>
        <td><%= ojdt.CreateDate %></td>
        <td><%= ojdt.UserSign %></td>
        <td><%= ojdt.UserSign2 %></td>
        <td><%= ojdt.RefndRprt %></td>
        <td><%= ojdt.LogInstanc %></td>
        <td><%= ojdt.ObjType %></td>
        <td><%= ojdt.Indicator %></td>
        <td><%= ojdt.AdjTran %></td>
        <td><%= ojdt.RevSource %></td>
        <td><%= ojdt.StornoDate %></td>
        <td><%= ojdt.StornoToTr %></td>
        <td><%= ojdt.AutoStorno %></td>
        <td><%= ojdt.Corisptivi %></td>
        <td><%= ojdt.VatDate %></td>
        <td><%= ojdt.StampTax %></td>
        <td><%= ojdt.Series %></td>
        <td><%= ojdt.Number %></td>
        <td><%= ojdt.AutoVAT %></td>
        <td><%= ojdt.DocSeries %></td>
        <td><%= ojdt.FolioPref %></td>
        <td><%= ojdt.FolioNum %></td>
        <td><%= ojdt.CreateTime %></td>
        <td><%= ojdt.BlockDunn %></td>
        <td><%= ojdt.ReportEU %></td>
        <td><%= ojdt.Report347 %></td>
        <td><%= ojdt.Printed %></td>
        <td><%= ojdt.DocType %></td>
        <td><%= ojdt.AttNum %></td>
        <td><%= ojdt.GenRegNo %></td>
        <td><%= ojdt.RG23APart2 %></td>
        <td><%= ojdt.RG23CPart2 %></td>
        <td><%= ojdt.MatType %></td>
        <td><%= ojdt.Creator %></td>
        <td><%= ojdt.Approver %></td>
        <td><%= ojdt.Location %></td>
        <td><%= ojdt.SeqCode %></td>
        <td><%= ojdt.Serial %></td>
        <td><%= ojdt.SeriesStr %></td>
        <td><%= ojdt.SubStr %></td>
        <td><%= ojdt.AutoWT %></td>
        <td><%= ojdt.WTSum %></td>
        <td><%= ojdt.WTSumSC %></td>
        <td><%= ojdt.WTSumFC %></td>
        <td><%= ojdt.WTApplied %></td>
        <td><%= ojdt.WTAppliedS %></td>
        <td><%= ojdt.WTAppliedF %></td>
        <td><%= ojdt.BaseAmnt %></td>
        <td><%= ojdt.BaseAmntSC %></td>
        <td><%= ojdt.BaseAmntFC %></td>
        <td><%= ojdt.BaseVtAt %></td>
        <td><%= ojdt.BaseVtAtSC %></td>
        <td><%= ojdt.BaseVtAtFC %></td>
        <td><%= ojdt.VersionNum %></td>
        <td><%= ojdt.BaseTrans %></td>
        <td><%= ojdt.ResidenNum %></td>
        <td><%= ojdt.OperatCode %></td>
        <td><%= ojdt.Ref3 %></td>
        <td><%= ojdt.SSIExmpt %></td>
        <td><%= ojdt.SignMsg %></td>
        <td><%= ojdt.SignDigest %></td>
        <td><%= ojdt.CertifNum %></td>
        <td><%= ojdt.KeyVersion %></td>
        <td><%= ojdt.CUP %></td>
        <td><%= ojdt.CIG %></td>
        <td><%= ojdt.SupplCode %></td>
        <td><%= ojdt.SPSrcType %></td>
        <td><%= ojdt.SPSrcID %></td>
        <td><%= ojdt.SPSrcDLN %></td>
        <td><%= ojdt.DeferedTax %></td>
        <td><%= ojdt.AgrNo %></td>
        <td><%= ojdt.SeqNum %></td>
        <td><%= link_to 'Show', ojdt %></td>
        <td><%= link_to 'Edit', edit_ojdt_path(ojdt) %></td>
        <td><%= link_to 'Destroy', ojdt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ojdt', new_ojdt_path %>

jdtapp.r5mysql/app/views/ojdts/new.html.erb
<h1>New Ojdt</h1>

<%= render 'form', ojdt: @ojdt %>

<%= link_to 'Back', ojdts_path %>

jdtapp.r5mysql/app/views/ojdts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batchnum:</strong>
  <%= @ojdt.BatchNum %>
</p>

<p>
  <strong>Transid:</strong>
  <%= @ojdt.TransId %>
</p>

<p>
  <strong>Btfstatus:</strong>
  <%= @ojdt.BtfStatus %>
</p>

<p>
  <strong>Transtype:</strong>
  <%= @ojdt.TransType %>
</p>

<p>
  <strong>Baseref:</strong>
  <%= @ojdt.BaseRef %>
</p>

<p>
  <strong>Refdate:</strong>
  <%= @ojdt.RefDate %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @ojdt.Memo %>
</p>

<p>
  <strong>Ref1:</strong>
  <%= @ojdt.Ref1 %>
</p>

<p>
  <strong>Ref2:</strong>
  <%= @ojdt.Ref2 %>
</p>

<p>
  <strong>Createdby:</strong>
  <%= @ojdt.CreatedBy %>
</p>

<p>
  <strong>Loctotal:</strong>
  <%= @ojdt.LocTotal %>
</p>

<p>
  <strong>Fctotal:</strong>
  <%= @ojdt.FcTotal %>
</p>

<p>
  <strong>Systotal:</strong>
  <%= @ojdt.SysTotal %>
</p>

<p>
  <strong>Transcode:</strong>
  <%= @ojdt.TransCode %>
</p>

<p>
  <strong>Origncurr:</strong>
  <%= @ojdt.OrignCurr %>
</p>

<p>
  <strong>Transrate:</strong>
  <%= @ojdt.TransRate %>
</p>

<p>
  <strong>Btfline:</strong>
  <%= @ojdt.BtfLine %>
</p>

<p>
  <strong>Transcurr:</strong>
  <%= @ojdt.TransCurr %>
</p>

<p>
  <strong>Project:</strong>
  <%= @ojdt.Project %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @ojdt.DueDate %>
</p>

<p>
  <strong>Taxdate:</strong>
  <%= @ojdt.TaxDate %>
</p>

<p>
  <strong>Pcaddition:</strong>
  <%= @ojdt.PCAddition %>
</p>

<p>
  <strong>Finncpriod:</strong>
  <%= @ojdt.FinncPriod %>
</p>

<p>
  <strong>Datasource:</strong>
  <%= @ojdt.DataSource %>
</p>

<p>
  <strong>Updatedate:</strong>
  <%= @ojdt.UpdateDate %>
</p>

<p>
  <strong>Createdate:</strong>
  <%= @ojdt.CreateDate %>
</p>

<p>
  <strong>Usersign:</strong>
  <%= @ojdt.UserSign %>
</p>

<p>
  <strong>Usersign2:</strong>
  <%= @ojdt.UserSign2 %>
</p>

<p>
  <strong>Refndrprt:</strong>
  <%= @ojdt.RefndRprt %>
</p>

<p>
  <strong>Loginstanc:</strong>
  <%= @ojdt.LogInstanc %>
</p>

<p>
  <strong>Objtype:</strong>
  <%= @ojdt.ObjType %>
</p>

<p>
  <strong>Indicator:</strong>
  <%= @ojdt.Indicator %>
</p>

<p>
  <strong>Adjtran:</strong>
  <%= @ojdt.AdjTran %>
</p>

<p>
  <strong>Revsource:</strong>
  <%= @ojdt.RevSource %>
</p>

<p>
  <strong>Stornodate:</strong>
  <%= @ojdt.StornoDate %>
</p>

<p>
  <strong>Stornototr:</strong>
  <%= @ojdt.StornoToTr %>
</p>

<p>
  <strong>Autostorno:</strong>
  <%= @ojdt.AutoStorno %>
</p>

<p>
  <strong>Corisptivi:</strong>
  <%= @ojdt.Corisptivi %>
</p>

<p>
  <strong>Vatdate:</strong>
  <%= @ojdt.VatDate %>
</p>

<p>
  <strong>Stamptax:</strong>
  <%= @ojdt.StampTax %>
</p>

<p>
  <strong>Series:</strong>
  <%= @ojdt.Series %>
</p>

<p>
  <strong>Number:</strong>
  <%= @ojdt.Number %>
</p>

<p>
  <strong>Autovat:</strong>
  <%= @ojdt.AutoVAT %>
</p>

<p>
  <strong>Docseries:</strong>
  <%= @ojdt.DocSeries %>
</p>

<p>
  <strong>Foliopref:</strong>
  <%= @ojdt.FolioPref %>
</p>

<p>
  <strong>Folionum:</strong>
  <%= @ojdt.FolioNum %>
</p>

<p>
  <strong>Createtime:</strong>
  <%= @ojdt.CreateTime %>
</p>

<p>
  <strong>Blockdunn:</strong>
  <%= @ojdt.BlockDunn %>
</p>

<p>
  <strong>Reporteu:</strong>
  <%= @ojdt.ReportEU %>
</p>

<p>
  <strong>Report347:</strong>
  <%= @ojdt.Report347 %>
</p>

<p>
  <strong>Printed:</strong>
  <%= @ojdt.Printed %>
</p>

<p>
  <strong>Doctype:</strong>
  <%= @ojdt.DocType %>
</p>

<p>
  <strong>Attnum:</strong>
  <%= @ojdt.AttNum %>
</p>

<p>
  <strong>Genregno:</strong>
  <%= @ojdt.GenRegNo %>
</p>

<p>
  <strong>Rg23apart2:</strong>
  <%= @ojdt.RG23APart2 %>
</p>

<p>
  <strong>Rg23cpart2:</strong>
  <%= @ojdt.RG23CPart2 %>
</p>

<p>
  <strong>Mattype:</strong>
  <%= @ojdt.MatType %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @ojdt.Creator %>
</p>

<p>
  <strong>Approver:</strong>
  <%= @ojdt.Approver %>
</p>

<p>
  <strong>Location:</strong>
  <%= @ojdt.Location %>
</p>

<p>
  <strong>Seqcode:</strong>
  <%= @ojdt.SeqCode %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @ojdt.Serial %>
</p>

<p>
  <strong>Seriesstr:</strong>
  <%= @ojdt.SeriesStr %>
</p>

<p>
  <strong>Substr:</strong>
  <%= @ojdt.SubStr %>
</p>

<p>
  <strong>Autowt:</strong>
  <%= @ojdt.AutoWT %>
</p>

<p>
  <strong>Wtsum:</strong>
  <%= @ojdt.WTSum %>
</p>

<p>
  <strong>Wtsumsc:</strong>
  <%= @ojdt.WTSumSC %>
</p>

<p>
  <strong>Wtsumfc:</strong>
  <%= @ojdt.WTSumFC %>
</p>

<p>
  <strong>Wtapplied:</strong>
  <%= @ojdt.WTApplied %>
</p>

<p>
  <strong>Wtapplieds:</strong>
  <%= @ojdt.WTAppliedS %>
</p>

<p>
  <strong>Wtappliedf:</strong>
  <%= @ojdt.WTAppliedF %>
</p>

<p>
  <strong>Baseamnt:</strong>
  <%= @ojdt.BaseAmnt %>
</p>

<p>
  <strong>Baseamntsc:</strong>
  <%= @ojdt.BaseAmntSC %>
</p>

<p>
  <strong>Baseamntfc:</strong>
  <%= @ojdt.BaseAmntFC %>
</p>

<p>
  <strong>Basevtat:</strong>
  <%= @ojdt.BaseVtAt %>
</p>

<p>
  <strong>Basevtatsc:</strong>
  <%= @ojdt.BaseVtAtSC %>
</p>

<p>
  <strong>Basevtatfc:</strong>
  <%= @ojdt.BaseVtAtFC %>
</p>

<p>
  <strong>Versionnum:</strong>
  <%= @ojdt.VersionNum %>
</p>

<p>
  <strong>Basetrans:</strong>
  <%= @ojdt.BaseTrans %>
</p>

<p>
  <strong>Residennum:</strong>
  <%= @ojdt.ResidenNum %>
</p>

<p>
  <strong>Operatcode:</strong>
  <%= @ojdt.OperatCode %>
</p>

<p>
  <strong>Ref3:</strong>
  <%= @ojdt.Ref3 %>
</p>

<p>
  <strong>Ssiexmpt:</strong>
  <%= @ojdt.SSIExmpt %>
</p>

<p>
  <strong>Signmsg:</strong>
  <%= @ojdt.SignMsg %>
</p>

<p>
  <strong>Signdigest:</strong>
  <%= @ojdt.SignDigest %>
</p>

<p>
  <strong>Certifnum:</strong>
  <%= @ojdt.CertifNum %>
</p>

<p>
  <strong>Keyversion:</strong>
  <%= @ojdt.KeyVersion %>
</p>

<p>
  <strong>Cup:</strong>
  <%= @ojdt.CUP %>
</p>

<p>
  <strong>Cig:</strong>
  <%= @ojdt.CIG %>
</p>

<p>
  <strong>Supplcode:</strong>
  <%= @ojdt.SupplCode %>
</p>

<p>
  <strong>Spsrctype:</strong>
  <%= @ojdt.SPSrcType %>
</p>

<p>
  <strong>Spsrcid:</strong>
  <%= @ojdt.SPSrcID %>
</p>

<p>
  <strong>Spsrcdln:</strong>
  <%= @ojdt.SPSrcDLN %>
</p>

<p>
  <strong>Deferedtax:</strong>
  <%= @ojdt.DeferedTax %>
</p>

<p>
  <strong>Agrno:</strong>
  <%= @ojdt.AgrNo %>
</p>

<p>
  <strong>Seqnum:</strong>
  <%= @ojdt.SeqNum %>
</p>

<%= link_to 'Edit', edit_ojdt_path(@ojdt) %> |
<%= link_to 'Back', ojdts_path %>