jdtapp.r4/config/routes.rb
Rails.application.routes.draw do
  resources :ojdta
  resources :ojdts

end

jdtapp.r4/app/models/ojdt.rb
class Ojdt < ActiveRecord::Base
 self.table_name = "OJDT"
    
end

jdtapp.r4/app/models/ojdtum.rb
class Ojdtum < ActiveRecord::Base
	 self.table_name = "OJDT"

end

jdtapp.r4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jdtapp.r4/app/controllers/ojdta_controller.rb
class OjdtaController < ApplicationController
  before_action :set_ojdtum, only: [:show, :edit, :update, :destroy]

  # GET /ojdta
  # GET /ojdta.json
  def index
    @ojdta = Ojdtum.all
  end

  # GET /ojdta/1
  # GET /ojdta/1.json
  def show
  end

  # GET /ojdta/new
  def new
    @ojdtum = Ojdtum.new
  end

  # GET /ojdta/1/edit
  def edit
  end

  # POST /ojdta
  # POST /ojdta.json
  def create
    @ojdtum = Ojdtum.new(ojdtum_params)

    respond_to do |format|
      if @ojdtum.save
        format.html { redirect_to @ojdtum, notice: 'Ojdtum was successfully created.' }
        format.json { render :show, status: :created, location: @ojdtum }
      else
        format.html { render :new }
        format.json { render json: @ojdtum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ojdta/1
  # PATCH/PUT /ojdta/1.json
  def update
    respond_to do |format|
      if @ojdtum.update(ojdtum_params)
        format.html { redirect_to @ojdtum, notice: 'Ojdtum was successfully updated.' }
        format.json { render :show, status: :ok, location: @ojdtum }
      else
        format.html { render :edit }
        format.json { render json: @ojdtum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ojdta/1
  # DELETE /ojdta/1.json
  def destroy
    @ojdtum.destroy
    respond_to do |format|
      format.html { redirect_to ojdta_url, notice: 'Ojdtum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ojdtum
      @ojdtum = Ojdtum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ojdtum_params
      params.require(:ojdtum).permit(:BatchNum, :TransId, :BtfStatus, :TransType, :BaseRef, :RefDate, :Memo, :Ref1, :Ref2, :CreatedBy, :LocTotal, :FcTotal, :SysTotal, :TransCode, :OrignCurr, :TransRate, :BtfLine, :TransCurr, :Project, :DueDate, :TaxDate, :PCAddition, :FinncPriod, :DataSource, :UpdateDate, :CreateDate, :UserSign, :UserSign2, :RefndRprt, :LogInstanc, :ObjType, :Indicator, :AdjTran, :RevSource, :StornoDate, :StornoToTr, :AutoStorno, :Corisptivi, :VatDate, :StampTax, :Series, :Number, :AutoVAT, :DocSeries, :FolioPref, :FolioNum, :CreateTime, :BlockDunn, :ReportEU, :Report347, :Printed, :DocType, :AttNum, :GenRegNo, :RG23APart2, :RG23CPart2, :MatType, :Creator, :Approver, :Location, :SeqCode, :Serial, :SeriesStr, :SubStr, :AutoWT, :WTSum, :WTSumSC, :WTSumFC, :WTApplied, :WTAppliedS, :WTAppliedF, :BaseAmnt, :BaseAmntSC, :BaseAmntFC, :BaseVtAt, :BaseVtAtSC, :BaseVtAtFC, :VersionNum, :BaseTrans, :ResidenNum, :OperatCode, :Ref3, :SSIExmpt, :SignMsg, :SignDigest, :CertifNum, :KeyVersion, :CUP, :CIG, :SupplCode, :SPSrcType, :SPSrcID, :SPSrcDLN, :DeferedTax, :AgrNo, :SeqNum)
    end
end

jdtapp.r4/app/controllers/ojdts_controller.rb
class OjdtsController < ApplicationController
  before_action :set_ojdt, only: [:show, :edit, :update, :destroy]

  # GET /ojdts
  # GET /ojdts.json
  def index
    @ojdts = Ojdt.all
  end

  # GET /ojdts/1
  # GET /ojdts/1.json
  def show
  end

  # GET /ojdts/new
  def new
    @ojdt = Ojdt.new
  end

  # GET /ojdts/1/edit
  def edit
  end

  # POST /ojdts
  # POST /ojdts.json
  def create
    @ojdt = Ojdt.new(ojdt_params)

    respond_to do |format|
      if @ojdt.save
        format.html { redirect_to @ojdt, notice: 'Ojdt was successfully created.' }
        format.json { render :show, status: :created, location: @ojdt }
      else
        format.html { render :new }
        format.json { render json: @ojdt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ojdts/1
  # PATCH/PUT /ojdts/1.json
  def update
    respond_to do |format|
      if @ojdt.update(ojdt_params)
        format.html { redirect_to @ojdt, notice: 'Ojdt was successfully updated.' }
        format.json { render :show, status: :ok, location: @ojdt }
      else
        format.html { render :edit }
        format.json { render json: @ojdt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ojdts/1
  # DELETE /ojdts/1.json
  def destroy
    @ojdt.destroy
    respond_to do |format|
      format.html { redirect_to ojdts_url, notice: 'Ojdt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ojdt
      @ojdt = Ojdt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ojdt_params
      params.fetch(:ojdt, {})
    end
end

jdtapp.r4/app/controllers/pojdt_controller.rb
class PojdtController < ApplicationController
end

jdtapp.r4/app/helpers/application_helper.rb
module ApplicationHelper
end

jdtapp.r4/app/helpers/ojdta_helper.rb
module OjdtaHelper
end

jdtapp.r4/app/helpers/ojdts_helper.rb
module OjdtsHelper
end

jdtapp.r4/app/helpers/pojdt_helper.rb
module PojdtHelper
end

jdtapp.r4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JdtappR4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

jdtapp.r4/app/views/ojdta/edit.html.erb
<h1>Editing Ojdtum</h1>

<%= render 'form' %>

<%= link_to 'Show', @ojdtum %> |
<%= link_to 'Back', ojdta_path %>

jdtapp.r4/app/views/ojdta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ojdta</h1>

<table>
  <thead>
    <tr>
      <th>Batchnum</th>
      <th>Transid</th>
      <th>Btfstatus</th>
      <th>Transtype</th>
      <th>Baseref</th>
      <th>Refdate</th>
      <th>Memo</th>
      <th>Ref1</th>
      <th>Ref2</th>
      <th>Createdby</th>
      <th>Loctotal</th>
      <th>Fctotal</th>
      <th>Systotal</th>
      <th>Transcode</th>
      <th>Origncurr</th>
      <th>Transrate</th>
      <th>Btfline</th>
      <th>Transcurr</th>
      <th>Project</th>
      <th>Duedate</th>
      <th>Taxdate</th>
      <th>Pcaddition</th>
      <th>Finncpriod</th>
      <th>Datasource</th>
      <th>Updatedate</th>
      <th>Createdate</th>
      <th>Usersign</th>
      <th>Usersign2</th>
      <th>Refndrprt</th>
      <th>Loginstanc</th>
      <th>Objtype</th>
      <th>Indicator</th>
      <th>Adjtran</th>
      <th>Revsource</th>
      <th>Stornodate</th>
      <th>Stornototr</th>
      <th>Autostorno</th>
      <th>Corisptivi</th>
      <th>Vatdate</th>
      <th>Stamptax</th>
      <th>Series</th>
      <th>Number</th>
      <th>Autovat</th>
      <th>Docseries</th>
      <th>Foliopref</th>
      <th>Folionum</th>
      <th>Createtime</th>
      <th>Blockdunn</th>
      <th>Reporteu</th>
      <th>Report347</th>
      <th>Printed</th>
      <th>Doctype</th>
      <th>Attnum</th>
      <th>Genregno</th>
      <th>Rg23apart2</th>
      <th>Rg23cpart2</th>
      <th>Mattype</th>
      <th>Creator</th>
      <th>Approver</th>
      <th>Location</th>
      <th>Seqcode</th>
      <th>Serial</th>
      <th>Seriesstr</th>
      <th>Substr</th>
      <th>Autowt</th>
      <th>Wtsum</th>
      <th>Wtsumsc</th>
      <th>Wtsumfc</th>
      <th>Wtapplied</th>
      <th>Wtapplieds</th>
      <th>Wtappliedf</th>
      <th>Baseamnt</th>
      <th>Baseamntsc</th>
      <th>Baseamntfc</th>
      <th>Basevtat</th>
      <th>Basevtatsc</th>
      <th>Basevtatfc</th>
      <th>Versionnum</th>
      <th>Basetrans</th>
      <th>Residennum</th>
      <th>Operatcode</th>
      <th>Ref3</th>
      <th>Ssiexmpt</th>
      <th>Signmsg</th>
      <th>Signdigest</th>
      <th>Certifnum</th>
      <th>Keyversion</th>
      <th>Cup</th>
      <th>Cig</th>
      <th>Supplcode</th>
      <th>Spsrctype</th>
      <th>Spsrcid</th>
      <th>Spsrcdln</th>
      <th>Deferedtax</th>
      <th>Agrno</th>
      <th>Seqnum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ojdta.each do |ojdtum| %>
      <tr>
        <td><%= ojdtum.BatchNum %></td>
        <td><%= ojdtum.TransId %></td>
        <td><%= ojdtum.BtfStatus %></td>
        <td><%= ojdtum.TransType %></td>
        <td><%= ojdtum.BaseRef %></td>
        <td><%= ojdtum.RefDate %></td>
        <td><%= ojdtum.Memo %></td>
        <td><%= ojdtum.Ref1 %></td>
        <td><%= ojdtum.Ref2 %></td>
        <td><%= ojdtum.CreatedBy %></td>
        <td><%= ojdtum.LocTotal %></td>
        <td><%= ojdtum.FcTotal %></td>
        <td><%= ojdtum.SysTotal %></td>
        <td><%= ojdtum.TransCode %></td>
        <td><%= ojdtum.OrignCurr %></td>
        <td><%= ojdtum.TransRate %></td>
        <td><%= ojdtum.BtfLine %></td>
        <td><%= ojdtum.TransCurr %></td>
        <td><%= ojdtum.Project %></td>
        <td><%= ojdtum.DueDate %></td>
        <td><%= ojdtum.TaxDate %></td>
        <td><%= ojdtum.PCAddition %></td>
        <td><%= ojdtum.FinncPriod %></td>
        <td><%= ojdtum.DataSource %></td>
        <td><%= ojdtum.UpdateDate %></td>
        <td><%= ojdtum.CreateDate %></td>
        <td><%= ojdtum.UserSign %></td>
        <td><%= ojdtum.UserSign2 %></td>
        <td><%= ojdtum.RefndRprt %></td>
        <td><%= ojdtum.LogInstanc %></td>
        <td><%= ojdtum.ObjType %></td>
        <td><%= ojdtum.Indicator %></td>
        <td><%= ojdtum.AdjTran %></td>
        <td><%= ojdtum.RevSource %></td>
        <td><%= ojdtum.StornoDate %></td>
        <td><%= ojdtum.StornoToTr %></td>
        <td><%= ojdtum.AutoStorno %></td>
        <td><%= ojdtum.Corisptivi %></td>
        <td><%= ojdtum.VatDate %></td>
        <td><%= ojdtum.StampTax %></td>
        <td><%= ojdtum.Series %></td>
        <td><%= ojdtum.Number %></td>
        <td><%= ojdtum.AutoVAT %></td>
        <td><%= ojdtum.DocSeries %></td>
        <td><%= ojdtum.FolioPref %></td>
        <td><%= ojdtum.FolioNum %></td>
        <td><%= ojdtum.CreateTime %></td>
        <td><%= ojdtum.BlockDunn %></td>
        <td><%= ojdtum.ReportEU %></td>
        <td><%= ojdtum.Report347 %></td>
        <td><%= ojdtum.Printed %></td>
        <td><%= ojdtum.DocType %></td>
        <td><%= ojdtum.AttNum %></td>
        <td><%= ojdtum.GenRegNo %></td>
        <td><%= ojdtum.RG23APart2 %></td>
        <td><%= ojdtum.RG23CPart2 %></td>
        <td><%= ojdtum.MatType %></td>
        <td><%= ojdtum.Creator %></td>
        <td><%= ojdtum.Approver %></td>
        <td><%= ojdtum.Location %></td>
        <td><%= ojdtum.SeqCode %></td>
        <td><%= ojdtum.Serial %></td>
        <td><%= ojdtum.SeriesStr %></td>
        <td><%= ojdtum.SubStr %></td>
        <td><%= ojdtum.AutoWT %></td>
        <td><%= ojdtum.WTSum %></td>
        <td><%= ojdtum.WTSumSC %></td>
        <td><%= ojdtum.WTSumFC %></td>
        <td><%= ojdtum.WTApplied %></td>
        <td><%= ojdtum.WTAppliedS %></td>
        <td><%= ojdtum.WTAppliedF %></td>
        <td><%= ojdtum.BaseAmnt %></td>
        <td><%= ojdtum.BaseAmntSC %></td>
        <td><%= ojdtum.BaseAmntFC %></td>
        <td><%= ojdtum.BaseVtAt %></td>
        <td><%= ojdtum.BaseVtAtSC %></td>
        <td><%= ojdtum.BaseVtAtFC %></td>
        <td><%= ojdtum.VersionNum %></td>
        <td><%= ojdtum.BaseTrans %></td>
        <td><%= ojdtum.ResidenNum %></td>
        <td><%= ojdtum.OperatCode %></td>
        <td><%= ojdtum.Ref3 %></td>
        <td><%= ojdtum.SSIExmpt %></td>
        <td><%= ojdtum.SignMsg %></td>
        <td><%= ojdtum.SignDigest %></td>
        <td><%= ojdtum.CertifNum %></td>
        <td><%= ojdtum.KeyVersion %></td>
        <td><%= ojdtum.CUP %></td>
        <td><%= ojdtum.CIG %></td>
        <td><%= ojdtum.SupplCode %></td>
        <td><%= ojdtum.SPSrcType %></td>
        <td><%= ojdtum.SPSrcID %></td>
        <td><%= ojdtum.SPSrcDLN %></td>
        <td><%= ojdtum.DeferedTax %></td>
        <td><%= ojdtum.AgrNo %></td>
        <td><%= ojdtum.SeqNum %></td>
        <td><%= link_to 'Show', ojdtum %></td>
        <td><%= link_to 'Edit', edit_ojdtum_path(ojdtum) %></td>
        <td><%= link_to 'Destroy', ojdtum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ojdtum', new_ojdtum_path %>

jdtapp.r4/app/views/ojdta/new.html.erb
<h1>New Ojdtum</h1>

<%= render 'form' %>

<%= link_to 'Back', ojdta_path %>

jdtapp.r4/app/views/ojdta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batchnum:</strong>
  <%= @ojdtum.BatchNum %>
</p>

<p>
  <strong>Transid:</strong>
  <%= @ojdtum.TransId %>
</p>

<p>
  <strong>Btfstatus:</strong>
  <%= @ojdtum.BtfStatus %>
</p>

<p>
  <strong>Transtype:</strong>
  <%= @ojdtum.TransType %>
</p>

<p>
  <strong>Baseref:</strong>
  <%= @ojdtum.BaseRef %>
</p>

<p>
  <strong>Refdate:</strong>
  <%= @ojdtum.RefDate %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @ojdtum.Memo %>
</p>

<p>
  <strong>Ref1:</strong>
  <%= @ojdtum.Ref1 %>
</p>

<p>
  <strong>Ref2:</strong>
  <%= @ojdtum.Ref2 %>
</p>

<p>
  <strong>Createdby:</strong>
  <%= @ojdtum.CreatedBy %>
</p>

<p>
  <strong>Loctotal:</strong>
  <%= @ojdtum.LocTotal %>
</p>

<p>
  <strong>Fctotal:</strong>
  <%= @ojdtum.FcTotal %>
</p>

<p>
  <strong>Systotal:</strong>
  <%= @ojdtum.SysTotal %>
</p>

<p>
  <strong>Transcode:</strong>
  <%= @ojdtum.TransCode %>
</p>

<p>
  <strong>Origncurr:</strong>
  <%= @ojdtum.OrignCurr %>
</p>

<p>
  <strong>Transrate:</strong>
  <%= @ojdtum.TransRate %>
</p>

<p>
  <strong>Btfline:</strong>
  <%= @ojdtum.BtfLine %>
</p>

<p>
  <strong>Transcurr:</strong>
  <%= @ojdtum.TransCurr %>
</p>

<p>
  <strong>Project:</strong>
  <%= @ojdtum.Project %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @ojdtum.DueDate %>
</p>

<p>
  <strong>Taxdate:</strong>
  <%= @ojdtum.TaxDate %>
</p>

<p>
  <strong>Pcaddition:</strong>
  <%= @ojdtum.PCAddition %>
</p>

<p>
  <strong>Finncpriod:</strong>
  <%= @ojdtum.FinncPriod %>
</p>

<p>
  <strong>Datasource:</strong>
  <%= @ojdtum.DataSource %>
</p>

<p>
  <strong>Updatedate:</strong>
  <%= @ojdtum.UpdateDate %>
</p>

<p>
  <strong>Createdate:</strong>
  <%= @ojdtum.CreateDate %>
</p>

<p>
  <strong>Usersign:</strong>
  <%= @ojdtum.UserSign %>
</p>

<p>
  <strong>Usersign2:</strong>
  <%= @ojdtum.UserSign2 %>
</p>

<p>
  <strong>Refndrprt:</strong>
  <%= @ojdtum.RefndRprt %>
</p>

<p>
  <strong>Loginstanc:</strong>
  <%= @ojdtum.LogInstanc %>
</p>

<p>
  <strong>Objtype:</strong>
  <%= @ojdtum.ObjType %>
</p>

<p>
  <strong>Indicator:</strong>
  <%= @ojdtum.Indicator %>
</p>

<p>
  <strong>Adjtran:</strong>
  <%= @ojdtum.AdjTran %>
</p>

<p>
  <strong>Revsource:</strong>
  <%= @ojdtum.RevSource %>
</p>

<p>
  <strong>Stornodate:</strong>
  <%= @ojdtum.StornoDate %>
</p>

<p>
  <strong>Stornototr:</strong>
  <%= @ojdtum.StornoToTr %>
</p>

<p>
  <strong>Autostorno:</strong>
  <%= @ojdtum.AutoStorno %>
</p>

<p>
  <strong>Corisptivi:</strong>
  <%= @ojdtum.Corisptivi %>
</p>

<p>
  <strong>Vatdate:</strong>
  <%= @ojdtum.VatDate %>
</p>

<p>
  <strong>Stamptax:</strong>
  <%= @ojdtum.StampTax %>
</p>

<p>
  <strong>Series:</strong>
  <%= @ojdtum.Series %>
</p>

<p>
  <strong>Number:</strong>
  <%= @ojdtum.Number %>
</p>

<p>
  <strong>Autovat:</strong>
  <%= @ojdtum.AutoVAT %>
</p>

<p>
  <strong>Docseries:</strong>
  <%= @ojdtum.DocSeries %>
</p>

<p>
  <strong>Foliopref:</strong>
  <%= @ojdtum.FolioPref %>
</p>

<p>
  <strong>Folionum:</strong>
  <%= @ojdtum.FolioNum %>
</p>

<p>
  <strong>Createtime:</strong>
  <%= @ojdtum.CreateTime %>
</p>

<p>
  <strong>Blockdunn:</strong>
  <%= @ojdtum.BlockDunn %>
</p>

<p>
  <strong>Reporteu:</strong>
  <%= @ojdtum.ReportEU %>
</p>

<p>
  <strong>Report347:</strong>
  <%= @ojdtum.Report347 %>
</p>

<p>
  <strong>Printed:</strong>
  <%= @ojdtum.Printed %>
</p>

<p>
  <strong>Doctype:</strong>
  <%= @ojdtum.DocType %>
</p>

<p>
  <strong>Attnum:</strong>
  <%= @ojdtum.AttNum %>
</p>

<p>
  <strong>Genregno:</strong>
  <%= @ojdtum.GenRegNo %>
</p>

<p>
  <strong>Rg23apart2:</strong>
  <%= @ojdtum.RG23APart2 %>
</p>

<p>
  <strong>Rg23cpart2:</strong>
  <%= @ojdtum.RG23CPart2 %>
</p>

<p>
  <strong>Mattype:</strong>
  <%= @ojdtum.MatType %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @ojdtum.Creator %>
</p>

<p>
  <strong>Approver:</strong>
  <%= @ojdtum.Approver %>
</p>

<p>
  <strong>Location:</strong>
  <%= @ojdtum.Location %>
</p>

<p>
  <strong>Seqcode:</strong>
  <%= @ojdtum.SeqCode %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @ojdtum.Serial %>
</p>

<p>
  <strong>Seriesstr:</strong>
  <%= @ojdtum.SeriesStr %>
</p>

<p>
  <strong>Substr:</strong>
  <%= @ojdtum.SubStr %>
</p>

<p>
  <strong>Autowt:</strong>
  <%= @ojdtum.AutoWT %>
</p>

<p>
  <strong>Wtsum:</strong>
  <%= @ojdtum.WTSum %>
</p>

<p>
  <strong>Wtsumsc:</strong>
  <%= @ojdtum.WTSumSC %>
</p>

<p>
  <strong>Wtsumfc:</strong>
  <%= @ojdtum.WTSumFC %>
</p>

<p>
  <strong>Wtapplied:</strong>
  <%= @ojdtum.WTApplied %>
</p>

<p>
  <strong>Wtapplieds:</strong>
  <%= @ojdtum.WTAppliedS %>
</p>

<p>
  <strong>Wtappliedf:</strong>
  <%= @ojdtum.WTAppliedF %>
</p>

<p>
  <strong>Baseamnt:</strong>
  <%= @ojdtum.BaseAmnt %>
</p>

<p>
  <strong>Baseamntsc:</strong>
  <%= @ojdtum.BaseAmntSC %>
</p>

<p>
  <strong>Baseamntfc:</strong>
  <%= @ojdtum.BaseAmntFC %>
</p>

<p>
  <strong>Basevtat:</strong>
  <%= @ojdtum.BaseVtAt %>
</p>

<p>
  <strong>Basevtatsc:</strong>
  <%= @ojdtum.BaseVtAtSC %>
</p>

<p>
  <strong>Basevtatfc:</strong>
  <%= @ojdtum.BaseVtAtFC %>
</p>

<p>
  <strong>Versionnum:</strong>
  <%= @ojdtum.VersionNum %>
</p>

<p>
  <strong>Basetrans:</strong>
  <%= @ojdtum.BaseTrans %>
</p>

<p>
  <strong>Residennum:</strong>
  <%= @ojdtum.ResidenNum %>
</p>

<p>
  <strong>Operatcode:</strong>
  <%= @ojdtum.OperatCode %>
</p>

<p>
  <strong>Ref3:</strong>
  <%= @ojdtum.Ref3 %>
</p>

<p>
  <strong>Ssiexmpt:</strong>
  <%= @ojdtum.SSIExmpt %>
</p>

<p>
  <strong>Signmsg:</strong>
  <%= @ojdtum.SignMsg %>
</p>

<p>
  <strong>Signdigest:</strong>
  <%= @ojdtum.SignDigest %>
</p>

<p>
  <strong>Certifnum:</strong>
  <%= @ojdtum.CertifNum %>
</p>

<p>
  <strong>Keyversion:</strong>
  <%= @ojdtum.KeyVersion %>
</p>

<p>
  <strong>Cup:</strong>
  <%= @ojdtum.CUP %>
</p>

<p>
  <strong>Cig:</strong>
  <%= @ojdtum.CIG %>
</p>

<p>
  <strong>Supplcode:</strong>
  <%= @ojdtum.SupplCode %>
</p>

<p>
  <strong>Spsrctype:</strong>
  <%= @ojdtum.SPSrcType %>
</p>

<p>
  <strong>Spsrcid:</strong>
  <%= @ojdtum.SPSrcID %>
</p>

<p>
  <strong>Spsrcdln:</strong>
  <%= @ojdtum.SPSrcDLN %>
</p>

<p>
  <strong>Deferedtax:</strong>
  <%= @ojdtum.DeferedTax %>
</p>

<p>
  <strong>Agrno:</strong>
  <%= @ojdtum.AgrNo %>
</p>

<p>
  <strong>Seqnum:</strong>
  <%= @ojdtum.SeqNum %>
</p>

<%= link_to 'Edit', edit_ojdtum_path(@ojdtum) %> |
<%= link_to 'Back', ojdta_path %>